name: openbanking chart test
on:
  push:
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - 'charts/openbanking/**'
      - 'tests/**'

env:
  CHART: openbanking

jobs:
  test:
    name: Test chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint
      - name: Kubeconform lint
        run: make lint-kubeconform
      - name: Check kubernetes APIs
        run: make check-kube-apis
